### PR TITLE
Components events

### PR DESCRIPTION
**Pull request by alvp01**
In this pull request I added the logic to the components to perform math operations and store the results in the calculator state to show them in the calculator screen

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
Hi @alvp01, 

You have done an impressive job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Kindly make your readme more descriptive by adding the description of the project of what the project does. Remember that the readme is the first guide a user goes through when they visit your repo.

- [x] [**Optional**] It would be better to also add a screenshot of the project in  the readme.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alvp01** [comment]
> Hi @alvp01,
> 
> You have done an impressive job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes 
> * [x]  Kindly make your readme more descriptive by adding the description of the project of what the project does. Remember that the readme is the first guide a user goes through when they visit your repo.
> * [x]  [**Optional**] It would be better to also add a screenshot of the project in  the readme.
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> ## _Slack: Oloo Moses_
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Done. Thanks

**Review by dasileker — APPROVED** [review]
## **Hi @alvp01,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alvp01** [comment]
> ## **Hi @alvp01,**
> ## **Congratulations! tada Project Approved white_check_mark**
> Your project is complete! There is nothing else to say other than... it's time to merge it rocket
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you for your work and time. Happy day!

**Pull request merged**
